### ISSUE TITLE
Can't start my server

### ISSUE THREAD

**Issue by tman5o** [ScerIO/PocketMine-MP-Android#81]
My Android device version is Android Q so I am in the beta. My device is a Pixel 2 xl

This is the error it gives me

Fatal error: Uncaught ErrorException: touch(): Utime failed: Invalid argument in phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php:92
Stack trace:
#0 [internal function]: pocketmine\utils\Utils::errorExceptionHandler(2, 'touch(): Utime ...', 'phar:///storage...', 92, Array)
#1 phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php(92): touch('/storage/emulat...')
#2 phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php(217): pocketmine\utils\MainLogger->__construct('/storage/emulat...')
#3 phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php(299): pocketmine\server()
#4 /storage/emulated/0/PocketMine-MP/PocketMine-MP.phar(1): require('phar:///storage...')
#5 {main}
thrown in phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php on line 92

**Comment by SergeShkurko** [comment]
@tman5o try https://github.com/ScerIO/PocketMine-MP-Android/issues/128#issuecomment-581162222

**Comment by tman5o** [comment]
> @tman5o try [#128 (comment)](https://github.com/ScerIO/PocketMine-MP-Android/issues/128#issuecomment-581162222)

I tried all of these steps and it still gives me a error

**Comment by tman5o** [comment]
Android 10
Different error


Fatal error: Uncaught ErrorException: touch(): Utime failed: Invalid argument in phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php:89
Stack trace:
#0 [internal function]: pocketmine\utils\Utils::errorExceptionHandler(2, 'touch(): Utime ...', 'phar:///storage...', 89, Array)
#1 phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php(89): touch('/storage/emulat...')
#2 phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php(244): pocketmine\utils\MainLogger->__construct('/storage/emulat...')
#3 phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php(296): pocketmine\server()
#4 /storage/emulated/0/PocketMine-MP/PocketMine-MP.phar(11): require('phar:///storage...')
#5 {main}
thrown in phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/MainLogger.php on line 89
> Server is not running
